### ISSUE TITLE
Not redirecting to success page

### ISSUE THREAD

**Issue by abman322** [Bereky/chapa-payment-express#2]
The page is not redirecting to the success page after successful payment is made, it says Cross-Origin Read Blocking (CORB) blocked cross-origin on the console. Is there a way to solve this because it was also happening on the code I wrote.

**Comment by Bereky** [comment]
Hello, thanks for the issue. You are right. A redirect should happen after a successful payment. This was not happening because, there were some changes in Chapa documentation regarding the parameters of the data object. Previously, the value in the callback_url param was used as a redirect URL. Now, a new param 'return_url' is being used for this function. 

Therefore, I've updated the data object by adding the return_url param and i'ts working fine. There are also a few changes I made on the API's. You might want to check them out.

The CORB is just a warning, and you should ignore it. If you are having any other issues, let me know.
